// =============================================================================
// SESAP — seed data, taxonomies, and reference data.
//
// This is the FIRST-RUN seed only. After the app runs once, live ticket data is
// read from localStorage (see context/AppContext.jsx). When the real backend
// arrives, these arrays are the shape the API should return.
// =============================================================================

export const APP_NAME = 'Stanbic IBTC Enterprise Support & Automation Platform'
export const APP_SHORT = 'SESAP'
export const APP_VERSION = '2.0.0'

// ---- Vocabularies -----------------------------------------------------------
export const STATUSES = ['open', 'in_progress', 'resolved', 'closed']
export const PRIORITIES = ['low', 'medium', 'high', 'urgent']
export const RISK_LEVELS = ['Low', 'Medium', 'High']
export const CHANNELS = ['Portal', 'Email', 'Phone', 'Chat', 'Branch', 'Automation']

export const DEPARTMENTS = [
  'Retail Banking',
  'Corporate Banking',
  'Digital Channels',
  'IT Operations',
  'Automation CoE',
  'Risk & Compliance',
]

export const TEAMS = [
  'Tier 1 Support',
  'Tier 2 Support',
  'Payments Operations',
  'Automation Team',
  'Infrastructure',
]

export const BUSINESS_SERVICES = [
  'Internet Banking',
  'Mobile App',
  'ATM Network',
  'Core Banking',
  'Card Services',
  'USSD Banking',
]

// Category → sub-categories
export const CATEGORIES = {
  Payments: ['Failed Transfer', 'Card Payment', 'Standing Order', 'FX Transaction'],
  'Digital Banking': ['Login Issue', 'App Crash', 'OTP / 2FA', 'Feature Request'],
  Accounts: ['Statement', 'Account Opening', 'KYC / Documents', 'Account Access'],
  Lending: ['Loan Application', 'Repayment', 'Interest Query'],
  'Automation / RPA': ['Robot Failure', 'Process Exception', 'Schedule Issue'],
  Infrastructure: ['Network', 'Core Banking', 'Integration / API'],
  // Internal staff requests — these ALWAYS route to a supervisor for approval
  // before work proceeds (see needsApprovalOnCreate in utils.js).
  'Internal Requests': ['Purchase Request', 'Reimbursement / Expense Claim', 'Vendor Contract', 'Travel & Logistics', 'Software / License Request', 'Facilities & Equipment'],
}

// Categories that require supervisor sign-off at creation time (procurement /
// finance / commitments raised by staff).
export const APPROVAL_ON_CREATE_CATEGORY = 'Internal Requests'

// ---- People -----------------------------------------------------------------
// NOTE: emails below are illustrative placeholders on the corporate domain.
// Replace with a real directory when the backend/SSO integration lands.
export const ENGINEERS = [
  { name: 'Kunle Adeyemi', email: 'kunle.adeyemi@stanbicibtc.com', team: 'Tier 2 Support', initials: 'KA' },
  { name: 'Ngozi Eze', email: 'ngozi.eze@stanbicibtc.com', team: 'Payments Operations', initials: 'NE' },
  { name: 'Tobi Martins', email: 'tobi.martins@stanbicibtc.com', team: 'Tier 1 Support', initials: 'TM' },
  { name: 'Chidi Okonkwo', email: 'chidi.okonkwo@stanbicibtc.com', team: 'Automation Team', initials: 'CO' },
  { name: 'Fatima Sani', email: 'fatima.sani@stanbicibtc.com', team: 'Infrastructure', initials: 'FS' },
  { name: 'Emeka Obi', email: 'emeka.obi@stanbicibtc.com', team: 'Tier 2 Support', initials: 'EO' },
]

export const engineerByName = (name) => ENGINEERS.find((e) => e.name === name) || null

// ---- Seed tickets -----------------------------------------------------------
const ev = (type, text, at, author = 'System') => ({ type, text, at, author })

export const sampleTickets = [
  {
    id: 1042,
    ref: 'SESAP-1042',
    subject: 'Internet Banking login fails after password reset',
    description:
      'Customer reset their password via the email link but the new credentials are rejected on the login screen. Suspect the reset token is not invalidating the old hash.',
    requester: 'Aisha Bello',
    requesterEmail: 'aisha.bello@example.com',
    status: 'open',
    priority: 'urgent',
    category: 'Digital Banking',
    subCategory: 'Login Issue',
    department: 'Digital Channels',
    channel: 'Portal',
    team: 'Tier 2 Support',
    assignee: 'Kunle Adeyemi',
    assigneeEmail: 'kunle.adeyemi@stanbicibtc.com',
    businessService: 'Internet Banking',
    riskLevel: 'High',
    tags: ['auth', 'password-reset', 'vip'],
    escalated: true,
    createdAt: '2026-07-14T09:12:00Z',
    updatedAt: '2026-07-15T08:03:00Z',
    attachments: [],
    activity: [
      ev('created', 'Ticket created via Portal', '2026-07-14T09:12:00Z'),
      ev('comment', 'Reproduced on staging — escalating to auth team.', '2026-07-14T14:20:00Z', 'Kunle Adeyemi'),
      ev('status', 'Escalated to Tier 2', '2026-07-14T14:25:00Z', 'Kunle Adeyemi'),
    ],
  },
  {
    id: 1041,
    ref: 'SESAP-1041',
    subject: 'Corporate invoice billed in wrong currency',
    description: 'EUR account is being billed in USD on the July invoice. Needs correction and a reissue.',
    requester: 'Michael Okoro',
    requesterEmail: 'm.okoro@example.com',
    status: 'in_progress',
    priority: 'high',
    category: 'Payments',
    subCategory: 'FX Transaction',
    department: 'Corporate Banking',
    channel: 'Email',
    team: 'Payments Operations',
    assignee: 'Ngozi Eze',
    assigneeEmail: 'ngozi.eze@stanbicibtc.com',
    businessService: 'Core Banking',
    riskLevel: 'Medium',
    tags: ['billing', 'fx'],
    escalated: false,
    createdAt: '2026-07-13T15:40:00Z',
    updatedAt: '2026-07-15T07:20:00Z',
    attachments: [],
    activity: [ev('created', 'Ticket created via Email', '2026-07-13T15:40:00Z')],
  },
  {
    id: 1040,
    ref: 'SESAP-1040',
    subject: 'Request: export ticket analytics to Power BI',
    description: 'Dev team would like a way to export the full ticket list to CSV/Excel for reporting.',
    requester: 'ACME Dev Team',
    requesterEmail: 'dev.team@acme.io',
    status: 'open',
    priority: 'low',
    category: 'Digital Banking',
    subCategory: 'Feature Request',
    department: 'Digital Channels',
    channel: 'Portal',
    team: 'Tier 1 Support',
    assignee: null,
    assigneeEmail: null,
    businessService: 'Internet Banking',
    riskLevel: 'Low',
    tags: ['reporting'],
    escalated: false,
    createdAt: '2026-07-13T11:05:00Z',
    updatedAt: '2026-07-13T11:05:00Z',
    attachments: [],
    activity: [ev('created', 'Ticket created via Portal', '2026-07-13T11:05:00Z')],
  },
  {
    id: 1039,
    ref: 'SESAP-1039',
    subject: 'Mobile App crashes on Android 14 opening camera for cheque deposit',
    description: 'Hard crash the moment the camera permission dialog would appear. Only on Android 14 devices.',
    requester: 'Tunde Falana',
    requesterEmail: 'tunde.f@example.com',
    status: 'in_progress',
    priority: 'urgent',
    category: 'Digital Banking',
    subCategory: 'App Crash',
    department: 'Digital Channels',
    channel: 'Chat',
    team: 'Tier 2 Support',
    assignee: 'Kunle Adeyemi',
    assigneeEmail: 'kunle.adeyemi@stanbicibtc.com',
    businessService: 'Mobile App',
    riskLevel: 'High',
    tags: ['mobile', 'android', 'crash'],
    escalated: true,
    createdAt: '2026-07-12T18:22:00Z',
    updatedAt: '2026-07-14T16:45:00Z',
    attachments: [],
    activity: [
      ev('created', 'Ticket created via Chat', '2026-07-12T18:22:00Z'),
      ev('comment', 'Got the stack trace, looks like a permissions API change.', '2026-07-13T10:00:00Z', 'Kunle Adeyemi'),
    ],
  },
  {
    id: 1038,
    ref: 'SESAP-1038',
    subject: 'How to add a second admin user to corporate portal',
    description: 'Customer wants to grant admin access to a colleague and cannot find the setting.',
    requester: 'Grace Mensah',
    requesterEmail: 'grace.mensah@example.com',
    status: 'resolved',
    priority: 'medium',
    category: 'Accounts',
    subCategory: 'Account Access',
    department: 'Corporate Banking',
    channel: 'Phone',
    team: 'Tier 1 Support',
    assignee: 'Ngozi Eze',
    assigneeEmail: 'ngozi.eze@stanbicibtc.com',
    businessService: 'Internet Banking',
    riskLevel: 'Low',
    tags: ['how-to', 'admin'],
    escalated: false,
    createdAt: '2026-07-11T10:15:00Z',
    updatedAt: '2026-07-12T09:30:00Z',
    attachments: [],
    activity: [
      ev('created', 'Ticket created via Phone', '2026-07-11T10:15:00Z'),
      ev('comment', 'Sent walkthrough for Settings → Team → Invite admin.', '2026-07-12T09:30:00Z', 'Ngozi Eze'),
      ev('status', 'Marked resolved', '2026-07-12T09:30:00Z', 'Ngozi Eze'),
    ],
  },
  {
    id: 1037,
    ref: 'SESAP-1037',
    subject: 'Customer double-charged on card payment',
    description: 'Two identical charges appeared on the same day. Likely a duplicate webhook retry.',
    requester: 'Samuel Kalu',
    requesterEmail: 'samuel.k@example.com',
    status: 'open',
    priority: 'high',
    category: 'Payments',
    subCategory: 'Card Payment',
    department: 'Retail Banking',
    channel: 'Portal',
    team: 'Payments Operations',
    assignee: null,
    assigneeEmail: null,
    businessService: 'Card Services',
    riskLevel: 'High',
    tags: ['billing', 'duplicate-charge'],
    escalated: false,
    createdAt: '2026-07-11T08:00:00Z',
    updatedAt: '2026-07-11T08:00:00Z',
    attachments: [],
    activity: [ev('created', 'Ticket created via Portal', '2026-07-11T08:00:00Z')],
  },
  {
    id: 1036,
    ref: 'SESAP-1036',
    subject: 'Low contrast text on statements page (accessibility)',
    description: 'Low-contrast grey text on the dark settings background. Accessibility concern.',
    requester: 'Lola Ade',
    requesterEmail: 'lola.a@example.com',
    status: 'resolved',
    priority: 'low',
    category: 'Digital Banking',
    subCategory: 'Feature Request',
    department: 'Digital Channels',
    channel: 'Email',
    team: 'Tier 1 Support',
    assignee: 'Tobi Martins',
    assigneeEmail: 'tobi.martins@stanbicibtc.com',
    businessService: 'Internet Banking',
    riskLevel: 'Low',
    tags: ['a11y', 'ui'],
    escalated: false,
    createdAt: '2026-07-10T14:33:00Z',
    updatedAt: '2026-07-11T13:10:00Z',
    attachments: [],
    activity: [ev('created', 'Ticket created via Email', '2026-07-10T14:33:00Z')],
  },
  {
    id: 1035,
    ref: 'SESAP-1035',
    subject: 'API rate limit hit unexpectedly on partner integration',
    description: 'Customer hitting 429s well below their documented plan limit.',
    requester: 'FinTech Ops',
    requesterEmail: 'ops@fintechco.com',
    status: 'closed',
    priority: 'medium',
    category: 'Infrastructure',
    subCategory: 'Integration / API',
    department: 'IT Operations',
    channel: 'Email',
    team: 'Infrastructure',
    assignee: 'Fatima Sani',
    assigneeEmail: 'fatima.sani@stanbicibtc.com',
    businessService: 'Core Banking',
    riskLevel: 'Medium',
    tags: ['api', 'rate-limit'],
    escalated: false,
    createdAt: '2026-07-09T09:48:00Z',
    updatedAt: '2026-07-10T17:22:00Z',
    attachments: [],
    activity: [ev('created', 'Ticket created via Email', '2026-07-09T09:48:00Z')],
  },
  {
    id: 1034,
    ref: 'SESAP-1034',
    subject: 'Transactional emails landing in spam',
    description: 'Transactional emails landing in spam for Gmail recipients. Check SPF/DKIM.',
    requester: 'Chidi Nwosu',
    requesterEmail: 'chidi.n@example.com',
    status: 'closed',
    priority: 'low',
    category: 'Infrastructure',
    subCategory: 'Network',
    department: 'IT Operations',
    channel: 'Portal',
    team: 'Infrastructure',
    assignee: 'Fatima Sani',
    assigneeEmail: 'fatima.sani@stanbicibtc.com',
    businessService: 'Internet Banking',
    riskLevel: 'Low',
    tags: ['email', 'deliverability'],
    escalated: false,
    createdAt: '2026-07-08T12:00:00Z',
    updatedAt: '2026-07-09T10:05:00Z',
    attachments: [],
    activity: [ev('created', 'Ticket created via Portal', '2026-07-08T12:00:00Z')],
  },
  {
    id: 1033,
    ref: 'SESAP-1033',
    subject: 'Nightly reconciliation robot stuck at 90% for large accounts',
    description: 'Export job stalls near completion for accounts with >1M rows. Likely a timeout.',
    requester: 'BigCorp IT',
    requesterEmail: 'bigcorp.it@example.com',
    status: 'in_progress',
    priority: 'high',
    category: 'Automation / RPA',
    subCategory: 'Robot Failure',
    department: 'Automation CoE',
    channel: 'Automation',
    team: 'Automation Team',
    assignee: 'Chidi Okonkwo',
    assigneeEmail: 'chidi.okonkwo@stanbicibtc.com',
    businessService: 'Core Banking',
    riskLevel: 'High',
    tags: ['rpa', 'timeout', 'reconciliation'],
    escalated: true,
    createdAt: '2026-07-07T16:19:00Z',
    updatedAt: '2026-07-14T11:50:00Z',
    attachments: [],
    activity: [ev('created', 'Ticket created via Automation', '2026-07-07T16:19:00Z')],
  },
  {
    id: 1032,
    ref: 'SESAP-1032',
    subject: 'ATM cash dispense mismatch at Victoria Island branch',
    description: 'Reported dispense mismatch on ATM VI-014; journal shows successful dispense, customer disputes.',
    requester: 'Branch Ops VI',
    requesterEmail: 'vi.branch@example.com',
    status: 'open',
    priority: 'urgent',
    category: 'Payments',
    subCategory: 'Card Payment',
    department: 'Retail Banking',
    channel: 'Branch',
    team: 'Payments Operations',
    assignee: 'Ngozi Eze',
    assigneeEmail: 'ngozi.eze@stanbicibtc.com',
    businessService: 'ATM Network',
    riskLevel: 'High',
    tags: ['atm', 'dispute'],
    escalated: false,
    createdAt: '2026-07-15T06:30:00Z',
    updatedAt: '2026-07-15T06:30:00Z',
    attachments: [],
    activity: [ev('created', 'Ticket created via Branch', '2026-07-15T06:30:00Z')],
  },
  {
    id: 1030,
    ref: 'SESAP-1030',
    subject: 'Debit card declined at POS despite sufficient balance',
    description: 'My debit card was declined twice at a POS terminal this morning even though my account has funds.',
    requester: 'Aisha Bello',
    requesterEmail: 'aisha.bello@example.com',
    status: 'in_progress',
    priority: 'high',
    category: 'Payments',
    subCategory: 'Card Payment',
    department: 'Retail Banking',
    channel: 'Portal',
    team: 'Payments Operations',
    assignee: 'Ngozi Eze',
    assigneeEmail: 'ngozi.eze@stanbicibtc.com',
    businessService: 'Card Services',
    riskLevel: 'Medium',
    tags: ['card', 'pos'],
    escalated: false,
    createdAt: '2026-07-14T11:00:00Z',
    updatedAt: '2026-07-15T09:15:00Z',
    attachments: [],
    activity: [
      ev('created', 'Ticket created via Portal', '2026-07-14T11:00:00Z'),
      ev('comment', 'Thanks for reporting — we are checking the authorisation logs.', '2026-07-14T13:00:00Z', 'Ngozi Eze'),
    ],
  },
  {
    id: 1029,
    ref: 'SESAP-1029',
    subject: 'Request to increase daily transfer limit',
    description: 'I would like to increase my daily transfer limit for business payments.',
    requester: 'Aisha Bello',
    requesterEmail: 'aisha.bello@example.com',
    status: 'resolved',
    priority: 'low',
    category: 'Accounts',
    subCategory: 'Account Access',
    department: 'Retail Banking',
    channel: 'Portal',
    team: 'Tier 1 Support',
    assignee: 'Tobi Martins',
    assigneeEmail: 'tobi.martins@stanbicibtc.com',
    businessService: 'Internet Banking',
    riskLevel: 'Low',
    tags: ['limit'],
    escalated: false,
    createdAt: '2026-07-10T09:00:00Z',
    updatedAt: '2026-07-11T15:00:00Z',
    attachments: [],
    activity: [
      ev('created', 'Ticket created via Portal', '2026-07-10T09:00:00Z'),
      ev('comment', 'Your limit has been increased. Please allow 1 hour to reflect.', '2026-07-11T15:00:00Z', 'Tobi Martins'),
    ],
  },
  {
    id: 1031,
    ref: 'SESAP-1031',
    subject: 'USSD session timing out on airtime purchase',
    description: 'Customers report USSD *909# sessions dropping mid-flow during airtime purchase.',
    requester: 'Zainab Yusuf',
    requesterEmail: 'zainab.y@example.com',
    status: 'in_progress',
    priority: 'medium',
    category: 'Digital Banking',
    subCategory: 'App Crash',
    department: 'Digital Channels',
    channel: 'Phone',
    team: 'Tier 2 Support',
    assignee: 'Emeka Obi',
    assigneeEmail: 'emeka.obi@stanbicibtc.com',
    businessService: 'USSD Banking',
    riskLevel: 'Medium',
    tags: ['ussd', 'timeout'],
    escalated: false,
    createdAt: '2026-07-13T09:10:00Z',
    updatedAt: '2026-07-14T10:00:00Z',
    attachments: [],
    activity: [ev('created', 'Ticket created via Phone', '2026-07-13T09:10:00Z')],
  },
]

// ---- Knowledge Centre -------------------------------------------------------
export const knowledgeArticles = [
  {
    id: 'KB-001',
    title: 'How to safely reset a customer Internet Banking password',
    type: 'SOP',
    category: 'Digital Banking',
    updatedAt: '2026-07-10',
    summary: 'Step-by-step standard operating procedure for verified password resets, including token invalidation checks.',
  },
  {
    id: 'KB-002',
    title: 'Known Error: Android 14 camera permission crash',
    type: 'Known Error',
    category: 'Digital Banking',
    updatedAt: '2026-07-13',
    summary: 'Root cause and interim workaround for the cheque-deposit camera crash on Android 14 builds.',
  },
  {
    id: 'KB-003',
    title: 'Runbook: Reconciliation robot timeout recovery',
    type: 'Runbook',
    category: 'Automation / RPA',
    updatedAt: '2026-07-14',
    summary: 'Operational runbook to safely restart and checkpoint the nightly reconciliation robot after a stall.',
  },
  {
    id: 'KB-004',
    title: 'FAQ: Duplicate card charges and reversal timelines',
    type: 'FAQ',
    category: 'Payments',
    updatedAt: '2026-07-09',
    summary: 'Common questions on duplicate charges, provisional credits, and expected reversal windows.',
  },
  {
    id: 'KB-005',
    title: 'SOP: ATM dispense dispute investigation',
    type: 'SOP',
    category: 'Payments',
    updatedAt: '2026-07-12',
    summary: 'How to pull the electronic journal, match with switch logs, and raise a dispute case.',
  },
  {
    id: 'KB-006',
    title: 'Runbook: SPF/DKIM/DMARC email deliverability checks',
    type: 'Runbook',
    category: 'Infrastructure',
    updatedAt: '2026-07-08',
    summary: 'Verifying sender authentication records when transactional mail lands in spam.',
  },
]

// ---- Automation health (RPA robots) ----------------------------------------
export const automations = [
  { id: 'BOT-01', name: 'Nightly Reconciliation', status: 'warning', successRate: 82, runsToday: 3, lastRun: '2026-07-15T02:10:00Z' },
  { id: 'BOT-02', name: 'Statement Generation', status: 'healthy', successRate: 99, runsToday: 12, lastRun: '2026-07-15T07:00:00Z' },
  { id: 'BOT-03', name: 'KYC Document Validation', status: 'healthy', successRate: 97, runsToday: 44, lastRun: '2026-07-15T08:15:00Z' },
  { id: 'BOT-04', name: 'Card Dispute Intake', status: 'failed', successRate: 61, runsToday: 2, lastRun: '2026-07-15T05:40:00Z' },
  { id: 'BOT-05', name: 'Payment Retry Handler', status: 'healthy', successRate: 95, runsToday: 88, lastRun: '2026-07-15T08:20:00Z' },
  { id: 'BOT-06', name: 'Fraud Alert Triage', status: 'healthy', successRate: 93, runsToday: 27, lastRun: '2026-07-15T08:05:00Z' },
]

// ---- Announcements (landing + notifications) -------------------------------
export const announcements = [
  { id: 'A1', level: 'info', title: 'Scheduled maintenance', body: 'Core Banking maintenance window Sunday 02:00–04:00 WAT.', date: '2026-07-15' },
  { id: 'A2', level: 'success', title: 'SLA compliance at 94%', body: 'Support SLA compliance is up 6% month-on-month.', date: '2026-07-14' },
  { id: 'A3', level: 'warning', title: 'Reconciliation robot degraded', body: 'BOT-01 running at reduced success rate; Automation CoE engaged.', date: '2026-07-15' },
]

// ---- 14-day ticket volume trend (for dashboard line chart) -----------------
export const volumeTrend = [
  { d: 'Jul 2', created: 18, resolved: 15 },
  { d: 'Jul 3', created: 22, resolved: 19 },
  { d: 'Jul 4', created: 14, resolved: 17 },
  { d: 'Jul 5', created: 9, resolved: 11 },
  { d: 'Jul 6', created: 12, resolved: 10 },
  { d: 'Jul 7', created: 25, resolved: 20 },
  { d: 'Jul 8', created: 28, resolved: 24 },
  { d: 'Jul 9', created: 21, resolved: 23 },
  { d: 'Jul 10', created: 19, resolved: 22 },
  { d: 'Jul 11', created: 24, resolved: 18 },
  { d: 'Jul 12', created: 16, resolved: 20 },
  { d: 'Jul 13', created: 23, resolved: 21 },
  { d: 'Jul 14', created: 27, resolved: 25 },
  { d: 'Jul 15', created: 20, resolved: 12 },
]
